[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "10.12.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
