[build]
  command = "rm -rf node_modules && corepack enable && pnpm install --force && pnpm build"

[build.environment]
  PNPM_VERSION = "10.12.1"
  COREPACK_PREPARES_MAX_ATTEMPTS = "3" # Reinícios automáticos
